chore: added certs
MapColonies/Task-Liberator pull request #11
Opened 2022-01-25 11:22 UTC by CL-SHLOMIKONCHA

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore            | ✔/✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2022-01-25 12:42 UTC, shimoncohen requested changes

2022-01-25 12:42 UTC, shimoncohen commented on helm/values.yaml
> +    enabled: true
Should be false by default

2022-01-25 12:42 UTC, shimoncohen commented on helm/values.yaml
> +    enabled: true
Should be false by default

2022-01-25 14:47 UTC, shimoncohen approved these changes

2022-01-30 13:58 UTC, Yossizz approved these changes

2022-01-30 13:59 UTC, merged