fix: removed chart name from template names
MapColonies/Task-Liberator pull request #20
Opened 2023-09-07 10:48 UTC by nitzanmorr

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore            | ✔/✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2023-09-07 12:31 UTC, asafMasa requested changes

2023-09-07 12:31 UTC, asafMasa commented on helm/templates/_helpers.tpl
> +{{/*
not used

2023-09-07 13:23 UTC, CL-SHLOMIKONCHA commented on helm/templates/configmap.yaml
> +  name: {{ .Release.Name }}-configmap
change the configmap ref name in deployment aswell

2023-09-10 07:21 UTC, CL-SHLOMIKONCHA approved these changes

2023-09-10 07:37 UTC, merged