feat!: set the service to work as cron-job
MapColonies/Task-Liberator pull request #28
Opened 2024-08-14 13:53 UTC by netanelC

This PR makes the service to work as a cron-job. Every inerval of time (configurable) it executes.

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✔                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

This feature eliminate the dependency on OpenShift for scheduling and execution.
It solves the limitation of openshift we get in different networks and enhances the flexibility and reliability of our operations

2025-01-27 12:50 UTC, RonitKissis requested changes
update readme file

2025-01-27 12:50 UTC, RonitKissis commented on helm/Chart.yaml
should be automatically updated to 2.0.0 on run release workflow. otherwise will be bumped to 3.0.0

2025-01-27 12:50 UTC, RonitKissis commented on helm/templates/cron-job.yaml
rename file to deployment.yaml since it is not a cron-job anymore

2025-01-28 09:01 UTC, netanelC commented on helm/Chart.yaml
Done

2025-01-29 14:03 UTC, RonitKissis approved these changes
amazing job!

2025-01-29 14:03 UTC, RonitKissis requested changes
helm-lint fails

2025-01-30 07:27 UTC, RonitKissis approved these changes

2025-02-05 08:11 UTC, asafMasa requested changes

2025-02-05 08:11 UTC, asafMasa commented on src/index.ts
> +        const error = err as Error;
Please log the entire error and not just it's message, something like:
this.logger.error({
        msg: 'Main Loop error: ${error.message}',
        err,
      });

2025-02-05 08:11 UTC, asafMasa commented on src/index.ts
> +  setInterval(() => {
Instead of set interval, that will crash on single error, consider using this methodology:
`
const intervalMs = config.get<number>('intervalMs');

while (true) {
    try {
      await run(logger);
      await new Promise((resolve) => setTimeout(resolve, intervalMs));
    } catch (error) {
      // log error here
      await new Promise((resolve) => setTimeout(resolve, intervalMs));
    }
  }
`

2025-02-05 08:11 UTC, asafMasa commented on src/index.ts
> +  if (isActive) {
why do you need the "isActive" flag ?
what is the need of this?

2025-02-06 08:24 UTC, netanelC commented on src/index.ts
> +  if (isActive) {
Because in case the interval time is arrived and the service is still in-progress, the "run" function will know not to be executed

2025-02-06 08:24 UTC, netanelC commented on src/index.ts
> +  setInterval(() => {
It will not crash because the error is handled. In addition, it is better not to use `while true` in your code

2025-02-06 08:25 UTC, netanelC commented on src/index.ts
> +        const error = err as Error;
Done

2025-02-11 10:43 UTC, CL-SHLOMIKONCHA requested changes

2025-02-11 10:43 UTC, CL-SHLOMIKONCHA commented on config/custom-environment-variables.json
> +  "intervalMs": "INTERVAL_MS"
```suggestion
  "intervalMs": {
      "__name": "INTERVAL_MS",
      "__format": "number"
}
  
```

2025-02-11 13:15 UTC, asafMasa requested changes

2025-02-11 13:15 UTC, asafMasa commented on src/index.ts
> +  if (isActive) {
So why don't you use timers/promises in order to make sure the interval finishes before calling a new one?
https://nodejs.org/docs/v22.14.0/api/timers.html#timerspromisessetintervaldelay-value-options

2025-02-11 13:15 UTC, asafMasa commented on src/index.ts
> +  setInterval(() => {
Then please consider using https://nodejs.org/docs/v22.14.0/api/timers.html#timers-promises-api instead of the regular timers-api

2025-02-12 14:16 UTC, asafMasa approved these changes

2025-02-12 14:57 UTC, CL-SHLOMIKONCHA approved these changes
Approved, ** run prettier **

2025-02-19 17:32 UTC, merged